### ISSUE TITLE
Register with general registry

### ISSUE THREAD

**Issue by Longhao-Chen** [Longhao-Chen/BM3D.jl#1]
@JuliaRegistrator register

**Comment by johnnychen94** [comment]
This is really nice work!

The registry naming guideline does not allow all uppercase names. Maybe rename to BM3DDenoise.jl?

I also have an _experimenting_ package [ImageNoise.jl](https://github.com/JuliaImages/ImageNoise.jl) in JuliaImages, BM3D is on my to-do list for a long time so it would be great if you'd like to come and develop it together.

I'm recently playing with WNNM https://github.com/johnnychen94/WNNMDenoise.jl and BlockMatching https://github.com/johnnychen94/BlockMatching.jl and when it's finished I plan to add the WNNM codes to ImageNoise. The good news is that I've already made the WNNM 2-3x faster than the optimized Matlab version. I'm still experimenting with it because my expected runtime boost is ~10x.

My idea is to keep WNNMDenoise.jl as an archive for reproducing and benchmark purposes wrt the original paper, while ImageNoise.jl a toolbox for real applications. Or in other words, WNNMDenoise.jl targets researchers, and ImageNoise.jl targets the common users of JuliaImages. Hence if you like the idea of having a copy of it in ImageNoise.jl, perhaps there's no need to register in the General registry.

**Comment by Longhao-Chen** [comment]
Thanks for your help. This is my first package and I don't have much experience yet.

> Hence if you like the idea of having a copy of it in ImageNoise.jl

If it is possible, that's great.
So what should I do next? Do I need to rename it to BM3DDenoise.jl?

By the way, why not use Chinese? I think it's more convenient : )

**Comment by johnnychen94** [comment]
因为 WNNM 和 BM3D 都会经过一步 blockmatching 的过程，所以我一直在探索怎么样将这种 patch-based 方法给抽象出一个统一的接口出来，同时也在考虑怎么样规划并行的执行来让这一类算法的性能比较高，这些东西我自己也还有很不确定，所以暂时没有往 ImageNoise 里面加很多算法。(最近在写 BlockMatching 的 CUDA 版本）

如果你对于把 BM3D 加入到 ImageNoise 感兴趣的话，我可以到时候把代码加进去的时候 @ 你来一起，我之前没有复现过 BM3D 所以可能会有一些小细节没有你了解的清楚。因为最近比较忙所以如果我自己来做的话可能要到七月中下旬之后了。当然，如果你愿意直接提PR到 ImageNoise 的话我也可以直接给 review 然后给一些具体的建议。

如果是按照我所设想的这样计划的话，那么这个包注册或者不注册到 General 其实并没有太大差别。如果确实想要注册的话，那么可以考虑将 Images 这个依赖替换成 ImageCore + ...，这样的话依赖会小很多。

---

另一方面，JuliaImages 目前考虑的是 functor 的 API 设计，比较典型的是 https://github.com/zygmuntszpak/ImageBinarization.jl，对于 BM3D来说，它的 ImageNoise 版本就是：

```julia
alg = BM3D(args...)
denoised_img = reduce_noise(img, alg)
```

---

我留意到你使用的是 `group2image`/`image2group` 这种写法，实际上在 Julia 可以利用 view 来将这一操作简化，如果感兴趣的话可以看一看我写的实验文档 https://johnnychen94.github.io/LazyDistances.jl/dev/examples/image%20processing/block_matching/ 的 `patched_mean` 的实现。（换句话说，block matching 实际上并不需要提前对所有像素点进行计算）

**Comment by Longhao-Chen** [comment]
>因为 WNNM 和 BM3D 都会经过一步 blockmatching 的过程，所以我一直在探索怎么样将这种 patch-based 方法给抽象出一个统一的接口出来

这是一个非常好的想法，我最近可能有点忙，过段时间我会研究一下你的实现。

>如果你对于把 BM3D 加入到 ImageNoise 感兴趣的话，我可以到时候把代码加进去的时候 @ 你来一起，我之前没有复现过 BM3D 所以可能会有一些小细节没有你了解的清楚。

我的想法是：能否把 BM3D.jl 作为 ImageNoise.jl 的一个依赖包，在 ImageNoise.jl 中抽象出一个接口来？这样就只需维护一份代码了。因为我学 Julia 还不久，不清楚这样是否会有一些其它的问题，如果有感谢指出。

>另一方面，JuliaImages 目前考虑的是 functor 的 API 设计；
>我留意到你使用的是 `group2image`/`image2group` 这种写法，实际上在 Julia 可以利用 view 来将这一操作简化

看上去非常不错，我过段时间（可能要到7月份）将研究一下这一些。

**Comment by johnnychen94** [comment]
> >如果你对于把 BM3D 加入到 ImageNoise 感兴趣的话，我可以到时候把代码加进去的时候 @ 你来一起，我之前没有复现过 BM3D 所以可能会有一些小细节没有你了解的清楚。
>
> 我的想法是：能否把 BM3D.jl 作为 ImageNoise.jl 的一个依赖包，在 ImageNoise.jl 中抽象出一个接口来？这样就只需维护一份代码了。因为我学 Julia 还不久，不清楚这样是否会有一些其它的问题，如果有感谢指出。

我可能前面英文表述的不够清楚，我的设想是 BM3D.jl 作为一个复现和benchmark的包，尽可能地贴近原始 Matlab/C 实现的效果(比如说 PSNR 一致），一些算法研究者可以直接使用这个包来进行对比实验研究（这也是为什么我在 WNNMDenoise.jl 里面提供了 Manifest.toml 与 demo.jl 的原因）。另一方面，ImageNoise 里面额外提供一个针对具体去噪问题的 BM3D 算法，默认的参数与实现可能都会根据具体需求进行调整，相对来说会更自由一些，针对的用户是普通的图像处理用户而非去噪算法的研究者。你觉得呢？

如果对于论文的复现性没有任何要求的话，那么你设想的是完全可以做的。不过这个包可能需要重命名为 BM3DDenoise 才能正常在 General 里注册。

另外提一下，ImageQualityIndexes 里面提供了 PSNR 与 SSIM 的实现你可以直接使用 😆

**Comment by Longhao-Chen** [comment]
> 我可能前面英文表述的不够清楚，我的设想是 BM3D.jl 作为一个复现和benchmark的包，尽可能地贴近原始 Matlab/C 实现的效果(比如说 PSNR 一致），一些算法研究者可以直接使用这个包来进行对比实验研究（这也是为什么我在 WNNMDenoise.jl 里面提供了 Manifest.toml 与 demo.jl 的原因）。另一方面，ImageNoise 里面额外提供一个针对具体去噪问题的 BM3D 算法，默认的参数与实现可能都会根据具体需求进行调整，相对来说会更自由一些，针对的用户是普通的图像处理用户而非去噪算法的研究者。你觉得呢？

好，那就这样做。我最近先看看Julia的一些高级语法，并进行一些小的修改，到时候合并时我可以一起来。
